source ~/.config/zsh/01-env.zsh
source ~/.config/zsh/02-zshrc-system.zsh
source ~/.config/zsh/03-aliases.zsh
source ~/.config/zsh/04-fzf.zsh
source ~/.config/zsh/05-cursor-state.zsh
source ~/.config/zsh/other.zsh

# FIXME: 官方提供, 在 vsocde 的终端使用导致光标闪烁效果消失, 且使用 vim 后发现 normal 模式和 insert 为一样的方块光标状态, 猜测可能是脚本中有一些配置参数对 vscode terminal 支持有问题, 但是配置的代码太多了, 不想看...
# source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
# 这个不要和官方的一起用
# source ~/.config/zsh/vi-basic.zsh
# source ~/.config/zsh/vi.zsh
